# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exegesis', '0002_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(default='exegesis/static/project.jpg', max_length=200),
        ),
    ]
