# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exegesis', '0003_auto_20180817_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='density',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='screen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
