# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exegesis', '0004_auto_20180817_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('uuid', models.CharField(blank=True, max_length=50)),
                ('latest', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exegesis.Project')),
            ],
        ),
    ]
