# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exegesis', '0006_auto_20180817_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=200)),
                ('artboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exegesis.ArtBoard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exegesis.ArtBoard')),
            ],
        ),
    ]
