# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exegesis', '0007_note_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='share',
            new_name='shared',
        ),
        migrations.AddField(
            model_name='project',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
