# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exegesis', '0008_auto_20180819_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='shared',
        ),
    ]
